version: '3.8'

services:
  frontend:
    image: node
    container_name: frontend
    working_dir: /app/frontend
    command: npm start
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000