version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - frontend
    networks:
      - application

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    stdin_open: true
    tty: true
    networks:
      - application

networks:
  application:
    driver: bridge
